#PV with lables and PVC with selector
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume01
  labels:
    storage-tier: gold
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
      path: /var/local/data
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume02
spec:
  capacity:
    storage: 70Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
      path: /var/local/test

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 70Mi
  selector:
    matchLabels:
      storage-tier: gold
