apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-standard
  nfs:
    path: /var/nfs_server/kubernetes_data
    server: 10.25.96.6
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim01
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-standard
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: web-app
  template:
    metadata:
      labels:
        run: web-app
    spec:
      containers:
      - name: web-app
        image: nginx:latest
        ports:
         - containerPort: 80
        volumeMounts:
         - name: shared-volume01
           mountPath: "/usr/share/nginx/html"
      volumes:
      - name: shared-volume01
        persistentVolumeClaim:
          claimName: nfs-claim01
 
 ---
 
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    name: web-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
