apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pv-sc-access
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pv-sc-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: pod-access          
  namespace: dev #namespace of the service account
roleRef:
  kind: ClusterRole
  name: pv-sc-access
  apiGroup: rbac.authorization.k8s.io
