apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
spec:
  containers:
  - image: shamimice03/kubectl-image    
    name: kubectl-pod
    command:
    - sleep
    - "10000"
  serviceAccountName: pod-access
