apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: wordpress
      image: wordpress
      volumeMounts:
      - name: secret-vol01
        mountPath: /etc/secret    #files - mounted in this location
        readOnly: true
  volumes:
    - name: secret-vol01
      secret:
        secretName: app-secret
